### ISSUE TITLE
Question: best practice for listing search results

### ISSUE THREAD

**Issue by MPParsley** [nickveenhof/drupal8-umami-search#23]
At the moment we use "Rendered entity" in the search view.

Shouldn't we use the "Rendered HTML output" field as a best practice?

Or is that only a [best practice](https://www.drupal.org/project/search_api/issues/2742027#comment-11289229) when using search_api_solr.

PS: if we choose to change it, we shouldn't forget to
- remove the strip HTML processor for that field;
- disable auto_escaping for that field;

**Comment by nickveenhof** [comment]
@Nick_vh quick question: on http://drupalsear.ch we use "Rendered entity" in the search view. Shouldn't we use the "Rendered HTML output" field as a best practice?

Nick_vh [3:30 PM]
@mpp checking
rendered_item:
   label: ‘Rendered HTML output’
   property_path: rendered_item
isn’t it the rendered html output?
and it uses the search_index view mode to index it
so seems correct to me

mpp [3:34 PM]
My point is that in the view we use an entity view mode to render the output
vs the indexed field (which we use with search_api_solr for performance)

Nick_vh [3:35 PM]
ah - you don’t mean the index itself

mpp [3:35 PM]
indeed

Nick_vh [3:35 PM]
well that is a good point but given that it is not solr, there is no point in not doing that render
since that is cached and avoids a lot of the security concerns you otherwise would have

mpp [3:36 PM]
In the views config you can opt to show fields (the rendered output) or nodes (with a view mode)

Nick_vh [3:36 PM]
so it is best practice, but doesn’t mean it it the best option all the time

mpp [3:36 PM]
ok I agree, you can close my issue

Nick_vh [3:36 PM]
ideally you do not show the view mode from the index as that is filtered with the tokenizers
if you want to index the rendered item and you do not filter them, eg - just store it in a stored solr field -> yes that would be a feasable option
certainly for content repositories
but for a general search, nah :slightly_smiling_face:
at least that is my opinion
